services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: allvaps_stock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - allvaps_stock_db:/var/lib/postgresql/data
volumes:
  allvaps_stock_db:
