plugins { id 'com.android.application' }
android {
  namespace 'fr.allvaps.ava.device'
  compileSdk 34
  defaultConfig {
    applicationId "fr.allvaps.ava.device"
    minSdk 26
    targetSdk 34
    versionCode 1
    versionName "1.0.0"
  }
  buildTypes {
    release {
      minifyEnabled false
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}
